[package]
name = "hellman_attack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
whirlpool = "0.10.1"
rand = "0.8.5"
rayon = "1.7"
log = "0.4"
env_logger = "0.9"