[package]
name = "asymmetric_cryptography"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
statrs = "0.15"
num-traits = "0.2"
num-bigint = { version = "0.4", features = ["rand"] }